[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "rice-vpaa-sdk"
version = "0.1.0"
authors = [
  { name="Cody VanZandt", email="cav3@rice.edu" },
]
description = "SDK for the Rice VPAA API"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "pydantic>=2.0.0",
    "requests>=2.0.0",
]

[project.urls]
"Homepage" = "https://github.com/Rice-University-Academic-Affairs/VPAA-API"