[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "gabiking-pygame-widgets"
version = "1.0.2"
description = "This package provides widgets for a more friendly interface with PyGame."
authors = [{ name = "Gabriel" }]
dependencies = ["pygame"]
readme = "README.md"
license = { text = "MIT" }
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[tool.setuptools]
packages = ["gabiking_pygame_widgets"]
