[tool.poetry]
name = "scooterbot-agent"
version = "1.0.2"
description = ""
authors = ["Jimming Cheng <jimming@gmail.com>"]
readme = "README.md"
packages = [{include = "scooterbot_agent"}]

[tool.poetry.dependencies]
python = "^3.11"
openai = "^1.59.6"

[tool.poetry.group.dev.dependencies]
flake8 = "^7.1.1"
pytest = "^8.3.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
