[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "builder_maid"
version = "0.1.1"
authors = [
 { name="Thoru-san", email="thoru.fun@gmail.com" },
]
description = "Система сборки в рамках проекта maid."
readme = "README.md"
requires-python = ">=3.10.0"
classifiers = [
   "Programming Language :: Python :: 3",
   "License :: OSI Approved :: MIT License",
   "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/Thoru-san/builder_maid"
Issues = "https://github.com/Thoru-san/builder_maid"
