[project]
name = "killpy"
version = "0.15.0"
description = "List all .venv directories and Conda environments ðŸ on your system and check how much space they are using. You can then choose which ones to delete in order to free up space ðŸ§¹."
readme = "README.md"
classifiers = [
  "Environment :: Console",
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python :: 3.12"
]
dependencies = [
    "click>=8.1.8",
    "rich>=13.9.4",
    "textual>=1.0.0",
]
requires-python = ">=3.12"

[tool.setuptools]
license-files = []

[dependency-groups]
dev = [
    "commitizen>=4.1.0",
    "coverage>=7.6.10",
    "mypy>=1.14.0",
    "pre-commit>=4.0.1",
    "pytest>=8.3.4",
    "pytest-cov>=6.0.0",
    "ruff>=0.8.4",
]


[tool.uv.workspace]
members = ["q"]

[tool.uv]
package = true

[tool.commitizen]
name = "cz_conventional_commits"
version = "0.15.0"
version_files = [
    "src/__version__.py",
    "pyproject.toml:version"
]

[project.scripts]
killpy = "killpy.__main__:main"
