[tool.poetry]
name = "chatlabs-aiogram-support"
version = "0.1.1"
description = ""
authors = ["Rostislaww <rostiki.com@mail.ru>"]
readme = "README.md"
homepage = "https://github.com/RostHarcha/chatlabs-aiogram-support"
packages = [
    { include = "support" },
]

[tool.poetry.dependencies]
python = "^3.11"
aiogram = "^3.12.0"
aiogram-dialog = "^2.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
